"""create core tables

Revision ID: 5cb483d59152
Revises:
Create Date: 2026-07-15 20:49:54.072397
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5cb483d59152"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "processos",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("numero", sa.String(length=30), nullable=False),
        sa.Column(
            "tipo",
            sa.Enum(
                "marca", "patente", name="tipo_processo", native_enum=False, create_constraint=True
            ),
            nullable=False,
        ),
        sa.Column("titulo", sa.Text(), nullable=True),
        sa.Column("data_deposito", sa.Date(), nullable=True),
        sa.Column("situacao", sa.String(length=255), nullable=True),
        sa.Column("fonte", sa.String(length=100), nullable=False),
        sa.Column(
            "atualizado_em",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_processos_numero"), "processos", ["numero"], unique=True)
    op.create_index(op.f("ix_processos_situacao"), "processos", ["situacao"], unique=False)
    op.create_index(op.f("ix_processos_tipo"), "processos", ["tipo"], unique=False)
    op.create_table(
        "titulares",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("nome", sa.Text(), nullable=False),
        sa.Column("pais", sa.String(length=2), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_titulares_nome"), "titulares", ["nome"], unique=False)
    op.create_table(
        "movimentacoes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("processo_id", sa.BigInteger(), nullable=False),
        sa.Column("codigo_despacho", sa.String(length=30), nullable=True),
        sa.Column("descricao", sa.Text(), nullable=False),
        sa.Column("data_rpi", sa.Date(), nullable=False),
        sa.Column("numero_rpi", sa.Integer(), nullable=False),
        sa.Column("fonte_arquivo", sa.Text(), nullable=False),
        sa.Column("chave_origem", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["processo_id"], ["processos.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("chave_origem", name="uq_movimentacoes_chave_origem"),
    )
    op.create_index(
        op.f("ix_movimentacoes_codigo_despacho"), "movimentacoes", ["codigo_despacho"], unique=False
    )
    op.create_index(op.f("ix_movimentacoes_data_rpi"), "movimentacoes", ["data_rpi"], unique=False)
    op.create_index(
        op.f("ix_movimentacoes_numero_rpi"), "movimentacoes", ["numero_rpi"], unique=False
    )
    op.create_index(
        op.f("ix_movimentacoes_processo_id"), "movimentacoes", ["processo_id"], unique=False
    )
    op.create_table(
        "processo_titulares",
        sa.Column("processo_id", sa.BigInteger(), nullable=False),
        sa.Column("titular_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(["processo_id"], ["processos.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["titular_id"], ["titulares.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("processo_id", "titular_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("processo_titulares")
    op.drop_index(op.f("ix_movimentacoes_processo_id"), table_name="movimentacoes")
    op.drop_index(op.f("ix_movimentacoes_numero_rpi"), table_name="movimentacoes")
    op.drop_index(op.f("ix_movimentacoes_data_rpi"), table_name="movimentacoes")
    op.drop_index(op.f("ix_movimentacoes_codigo_despacho"), table_name="movimentacoes")
    op.drop_table("movimentacoes")
    op.drop_index(op.f("ix_titulares_nome"), table_name="titulares")
    op.drop_table("titulares")
    op.drop_index(op.f("ix_processos_tipo"), table_name="processos")
    op.drop_index(op.f("ix_processos_situacao"), table_name="processos")
    op.drop_index(op.f("ix_processos_numero"), table_name="processos")
    op.drop_table("processos")
    # ### end Alembic commands ###
